// VaultManager ABI - extracted from compiled contract
export const VAULT_MANAGER_ABI = [
  {
    type: 'impl',
    name: 'VaultManagerImpl',
    interface_name: 'starkyield::vault::vault_manager::IVaultManager',
  },
  {
    type: 'struct',
    name: 'core::integer::u256',
    members: [
      { name: 'low', type: 'core::integer::u128' },
      { name: 'high', type: 'core::integer::u128' },
    ],
  },
  {
    type: 'enum',
    name: 'core::bool',
    variants: [
      { name: 'False', type: '()' },
      { name: 'True', type: '()' },
    ],
  },
  {
    type: 'interface',
    name: 'starkyield::vault::vault_manager::IVaultManager',
    items: [
      {
        type: 'function',
        name: 'deposit',
        inputs: [{ name: 'amount', type: 'core::integer::u256' }],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'withdraw',
        inputs: [{ name: 'shares', type: 'core::integer::u256' }],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'rebalance',
        inputs: [],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'emergency_withdraw',
        inputs: [],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'set_paused',
        inputs: [{ name: 'paused', type: 'core::bool' }],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'set_target_leverage',
        inputs: [{ name: 'leverage', type: 'core::integer::u256' }],
        outputs: [],
        state_mutability: 'external',
      },
      {
        type: 'function',
        name: 'get_total_assets',
        inputs: [],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_share_price',
        inputs: [],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_health_factor',
        inputs: [],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_user_shares',
        inputs: [{ name: 'user', type: 'core::starknet::contract_address::ContractAddress' }],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_total_shares',
        inputs: [],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_btc_price',
        inputs: [],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
      {
        type: 'function',
        name: 'get_current_leverage',
        inputs: [],
        outputs: [{ type: 'core::integer::u256' }],
        state_mutability: 'view',
      },
    ],
  },
  {
    type: 'constructor',
    name: 'constructor',
    inputs: [
      { name: 'btc_token', type: 'core::starknet::contract_address::ContractAddress' },
      { name: 'usdc_token', type: 'core::starknet::contract_address::ContractAddress' },
      { name: 'sy_btc_token', type: 'core::starknet::contract_address::ContractAddress' },
      { name: 'ekubo_adapter', type: 'core::starknet::contract_address::ContractAddress' },
      { name: 'vesu_adapter', type: 'core::starknet::contract_address::ContractAddress' },
      { name: 'pragma_adapter', type: 'core::starknet::contract_address::ContractAddress' },
      { name: 'leverage_manager', type: 'core::starknet::contract_address::ContractAddress' },
      { name: 'owner', type: 'core::starknet::contract_address::ContractAddress' },
    ],
  },
  {
    type: 'event',
    name: 'starkyield::vault::vault_manager::VaultManager::Deposit',
    kind: 'struct',
    members: [
      { name: 'user', type: 'core::starknet::contract_address::ContractAddress', kind: 'key' },
      { name: 'amount', type: 'core::integer::u256', kind: 'data' },
      { name: 'shares', type: 'core::integer::u256', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'starkyield::vault::vault_manager::VaultManager::Withdraw',
    kind: 'struct',
    members: [
      { name: 'user', type: 'core::starknet::contract_address::ContractAddress', kind: 'key' },
      { name: 'shares', type: 'core::integer::u256', kind: 'data' },
      { name: 'amount', type: 'core::integer::u256', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'starkyield::vault::vault_manager::VaultManager::Rebalance',
    kind: 'struct',
    members: [
      { name: 'old_leverage', type: 'core::integer::u256', kind: 'data' },
      { name: 'new_leverage', type: 'core::integer::u256', kind: 'data' },
    ],
  },
  {
    type: 'event',
    name: 'starkyield::vault::vault_manager::VaultManager::Paused',
    kind: 'struct',
    members: [{ name: 'paused', type: 'core::bool', kind: 'data' }],
  },
  {
    type: 'event',
    name: 'starkyield::vault::vault_manager::VaultManager::EmergencyWithdraw',
    kind: 'struct',
    members: [{ name: 'total_btc_recovered', type: 'core::integer::u256', kind: 'data' }],
  },
  {
    type: 'event',
    name: 'starkyield::vault::vault_manager::VaultManager::Event',
    kind: 'enum',
    variants: [
      { name: 'Deposit', type: 'starkyield::vault::vault_manager::VaultManager::Deposit', kind: 'nested' },
      { name: 'Withdraw', type: 'starkyield::vault::vault_manager::VaultManager::Withdraw', kind: 'nested' },
      { name: 'Rebalance', type: 'starkyield::vault::vault_manager::VaultManager::Rebalance', kind: 'nested' },
      { name: 'Paused', type: 'starkyield::vault::vault_manager::VaultManager::Paused', kind: 'nested' },
      { name: 'EmergencyWithdraw', type: 'starkyield::vault::vault_manager::VaultManager::EmergencyWithdraw', kind: 'nested' },
    ],
  },
] as const;
